changed loop

diff --git a/run/archiveloop b/run/archiveloop
--- a/run/archiveloop
+++ b/run/archiveloop
@@ -340,6 +340,54 @@ function copy_music_files () {
   unmount_music_file
 }
 
+function move_clips_to_tmp() {
+  ROOT="$1"
+  SUB=$(basename "$ROOT")
+
+  log "Moving '$ROOT' to tmp folder"
+	
+  if [ ! -d "$ROOT" ]
+  then
+    log "$ROOT does not exist, skipping"
+    return
+  fi
+
+  while IFS= read -r -d '' file_name
+  do
+    if [ -d "$ROOT/$file_name" ]
+    then
+      log "Creating output directory '$SUB/$file_name' in tmp"
+      if ! mkdir -p "/tmp/$SUB/$file_name"
+      then
+        log "Failed to create '$SUB/$file_name' in tmp"
+        return
+      fi
+    elif [ -f "$ROOT/$file_name" ]
+    then
+      size=$(stat -c%s "$ROOT/$file_name")
+      if [ "$size" -lt 100000 ]
+      then
+        log "'$SUB/$file_name' is only $size bytes"
+        rm "$ROOT/$file_name"
+        NUM_FILES_DELETED=$((NUM_FILES_DELETED + 1))
+      else
+        log "Moving '$SUB/$file_name' to tmp"
+        outdir=$(dirname "$file_name")
+        if mv -f "$ROOT/$file_name" "/tmp/$SUB/$outdir"
+        then
+          log "Moved '$SUB/$file_name' to tmp"
+          NUM_FILES_MOVED=$((NUM_FILES_MOVED + 1))
+        else
+          log "Failed to move '$SUB/$file_name' to tmp"
+          NUM_FILES_FAILED=$((NUM_FILES_FAILED + 1))
+        fi
+      fi
+    else
+      log "$SUB/$file_name not found in tmp"
+    fi
+  done < <( find "$ROOT" -type f -printf "%P\0" )
+}
+
 function archive_clips () {
   log "Archiving..."
 
@@ -488,7 +536,7 @@ export -f log
 
 echo "==============================================" >> "$LOG_FILE"
 log "Starting archiveloop..."
-
+/root/bin/remountfs_rw
 mount_all_snapshots
 
 if [ "${SNAPSHOTS_ENABLED:-true}" = "true" ]
@@ -538,20 +586,21 @@ do
     /root/bin/make_snapshot.sh
   fi
 
-  #disconnect_usb_drives_from_host
+  disconnect_usb_drives_from_host
 
   mount_and_fix_errors_in_files
 
+  move_clips_to_tmp "$CAM_MOUNT/TeslaCam/SavedClips"
+  move_clips_to_tmp "$CAM_MOUNT/TeslaCam/SentryClips"
+  
+  connect_usb_drives_to_host
+  
   archive_clips
   
-  mount_and_fix_errors_in_files
-
   truncate_log
 
   doubleblink
 
-  #connect_usb_drives_to_host
-  
   log "Waiting 1 minute"
   sleep 1m
   
